name: main 

on:
  push:
    branches:
      - dev

jobs:
  compile:
    name: basic compiling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "dev"
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install 
      - run: npx truffle compile
      - run: npx truffle dev
      - run: npx truffle test test/1_masterdemon_test.js
