name: main 

on:
  push:
    branches:
      - dev

jobs:
  compile:
    name: basic compiling
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: "dev"

      - name: compile code
        run: npx truffle compile
      
